[runner]
# Override default compilers and/or interpreter
# Example c = "clang", cpp = "clang++", rust = "rustc" etc

[preset.debug]
c = "-g -Wall -Wextra"
cpp = "-g -Wall -Wextra -std=c++20"
rust = "-g"

[preset.release]
c = "-O3"
cpp = "-O3 -std=c++20"
rust = "-C opt-level=3"

# Custom languages support
# Add custom languages with their file extensions and runners
# type: "interpreter" (run directly) or "compiler" (compile then run)

# Example
# [language.csharp]
# extensions = [".cs"]
# runner = "dotnet"
# subcommand = "run"
# type = "interpreter"              # Change this to "compiler" if the language want to compile first
# flags = ["<flags>"]               # This is example for flags that will use during compiling
# arguments = ["<argument>"]